[project]
name = "pharma-playground"
version = "0.1.0"
description = "Pharma Voice Agent Playground"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "livekit-api"
]

[tool.setuptools]
packages = ["playground", "api"]
